# Generated by Django 3.2.5 on 2022-04-26 12:48

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='name')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='email')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='phone number')),
                ('language', models.CharField(blank=True, max_length=20, null=True, verbose_name='language')),
                ('currency', models.CharField(blank=True, max_length=5, null=True, verbose_name='currency')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
            ],
            options={
                'verbose_name': 'Provider',
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='price')),
                ('region', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326,
                                                                            verbose_name='region')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas',
                                               to='services.provider', verbose_name='areas')),
            ],
            options={
                'verbose_name': 'Service Areas',
            },
        ),
    ]
